---
version: '3.4'

services:

  pysnake:
    build:
      context: .
      target: pysnake
    environment:
      DISPLAY: ${DISPLAY}
    devices:
      - "/dev/snd"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
